Repository ossf-cve-benchmark/ossf-cve-benchmark, pull requests merged in 2020-12, with the labels that each got.

#3 Add CVE-2020-26256
  CVEs/CVE-2020-26256.json
Labels: CVE

#5 add config.json sample to the README.md example (#4)
  README.md
  docs/configuration.md
Labels: documentation

#11 Add sanity checks to install scripts
  contrib/tools/codeql/installers/install.sh
  contrib/tools/eslint/installers/install.sh
  contrib/tools/nodejsscan/installers/install.sh
Labels: enhancement
